package api

func (s *Server) registerRoutes() {
	// 1. System
	s.mux.HandleFunc("GET /api/system/status", s.handleSystemStatus)
	s.mux.HandleFunc("GET /api/system/menubar-status", s.handleSystemMenubarStatus)
	s.mux.HandleFunc("GET /api/system/diagnostics", s.adminOnly(s.handleSystemDiagnostics))
	s.mux.HandleFunc("GET /api/system/power", s.handleSystemPower)
	s.mux.HandleFunc("POST /api/system/power/toggle", s.adminOnly(s.handleSystemPowerToggle))
	s.mux.HandleFunc("GET /api/system/service", s.handleSystemServiceStatus)
	s.mux.HandleFunc("POST /api/system/service/install", s.adminOnly(s.handleSystemServiceInstall))
	s.mux.HandleFunc("POST /api/system/service/uninstall", s.adminOnly(s.handleSystemServiceUninstall))
	s.mux.HandleFunc("POST /api/system/service/no-open", s.adminOnly(s.handleSystemNoOpen))
	s.mux.HandleFunc("GET /api/system/backup", s.adminOnly(s.handleSystemBackupExport))
	s.mux.HandleFunc("POST /api/system/backup/restore", s.handleSystemBackupRestore)

	// 2. VM lifecycle & Specs
	s.mux.HandleFunc("GET /api/vm/prerequisites", s.adminOnly(s.handleVMPrerequisites))
	s.mux.HandleFunc("POST /api/vm/lima/install", s.adminOnly(s.handleVMInstallLima))
	s.mux.HandleFunc("POST /api/vm/start", s.adminOnly(s.handleVMStart))
	s.mux.HandleFunc("POST /api/vm/stop", s.adminOnly(s.handleVMStop))
	s.mux.HandleFunc("POST /api/vm/restart", s.adminOnly(s.handleVMRestart))
	s.mux.HandleFunc("GET /api/vm/config", s.handleVMConfigGet)
	s.mux.HandleFunc("POST /api/vm/config", s.adminOnly(s.handleVMConfigUpdate))
	s.mux.HandleFunc("GET /api/vm/listening-ports", s.adminOnly(s.handleVMListeningPorts))
	s.mux.HandleFunc("GET /api/vm/port-forwards", s.adminOnly(s.handleVMPortForwardsList))
	s.mux.HandleFunc("POST /api/vm/port-forwards", s.adminOnly(s.handleVMPortForwardPublish))
	s.mux.HandleFunc("DELETE /api/vm/port-forwards/{port}", s.adminOnly(s.handleVMPortForwardRemove))
	s.mux.HandleFunc("GET /api/jobs", s.adminOnly(s.handleJobsList))
	s.mux.HandleFunc("GET /api/jobs/{id}", s.adminOnly(s.handleJobGet))
	s.mux.HandleFunc("POST /api/jobs/{id}/cancel", s.adminOnly(s.handleJobCancel))
	s.mux.HandleFunc("POST /api/jobs/clear", s.adminOnly(s.handleJobsClear))

	// 3. Storage
	s.mux.HandleFunc("GET /api/storage/disks", s.handleStorageDisks)
	s.mux.HandleFunc("POST /api/storage/bind", s.adminOnly(s.handleStorageBind))
	s.mux.HandleFunc("POST /api/storage/unbind", s.adminOnly(s.handleStorageUnbind))
	s.mux.HandleFunc("POST /api/storage/bind-secondary", s.adminOnly(s.handleStorageBindSecondary))
	s.mux.HandleFunc("POST /api/storage/unbind-secondary", s.adminOnly(s.handleStorageUnbindSecondary))
	s.mux.HandleFunc("GET /api/storage/mounts", s.handleStorageMountsList)
	s.mux.HandleFunc("POST /api/storage/mounts", s.adminOnly(s.handleStorageMountsAdd))
	s.mux.HandleFunc("POST /api/storage/mounts/{id}/toggle", s.adminOnly(s.handleStorageMountsToggle))
	s.mux.HandleFunc("POST /api/storage/mounts/{id}/writable", s.adminOnly(s.handleStorageMountsWritable))
	s.mux.HandleFunc("DELETE /api/storage/mounts/{id}", s.adminOnly(s.handleStorageMountsDelete))
	s.mux.HandleFunc("POST /api/storage/pick-host-directory", s.adminOnly(s.handleStoragePickHostDirectory))
	// Remote cloud drives. Login is a short-lived web QR flow; credentials are
	// only accepted by the server after the provider confirms the session.
	s.mux.HandleFunc("POST /api/storage/cloud-auth/quark/qr", s.adminOnly(s.handleQuarkQRBegin))
	s.mux.HandleFunc("GET /api/storage/cloud-auth/quark/qr/{id}", s.handleQuarkQRPoll)
	s.mux.HandleFunc("GET /api/storage/cloud-auth/quark/qr/{id}/image", s.handleQuarkQRImage)
	s.mux.HandleFunc("POST /api/storage/cloud-mounts/quark/qr/{id}", s.adminOnly(s.handleQuarkMountFromQR))
	s.mux.HandleFunc("GET /api/storage/cloud-mounts", s.handleCloudMountsList)
	s.mux.HandleFunc("POST /api/storage/cloud-mounts/{id}/check", s.adminOnly(s.handleCloudMountCheck))
	s.mux.HandleFunc("DELETE /api/storage/cloud-mounts/{id}", s.adminOnly(s.handleCloudMountDelete))
	s.mux.HandleFunc("GET /api/storage/cloud-mounts/{id}/files", s.handleCloudFilesList)
	s.mux.HandleFunc("POST /api/storage/cloud-mounts/{id}/folders", s.adminOnly(s.handleCloudFolderCreate))
	s.mux.HandleFunc("POST /api/storage/cloud-mounts/{id}/rename", s.adminOnly(s.handleCloudFileRename))
	s.mux.HandleFunc("DELETE /api/storage/cloud-mounts/{id}/files", s.adminOnly(s.handleCloudFileDelete))
	s.mux.HandleFunc("POST /api/storage/cloud-mounts/{id}/copy", s.adminOnly(s.handleCloudFileCopy))
	s.mux.HandleFunc("POST /api/storage/cloud-mounts/{id}/move", s.adminOnly(s.handleCloudFileMove))
	s.mux.HandleFunc("POST /api/storage/cloud-mounts/{id}/upload", s.adminOnly(s.handleCloudUpload))
	s.mux.HandleFunc("POST /api/storage/cloud-mounts/{id}/download", s.adminOnly(s.handleCloudDownload))

	// 4. Docker Overview & Containers
	s.mux.HandleFunc("GET /api/docker/overview", s.handleDockerOverview)
	s.mux.HandleFunc("GET /api/docker/engine", s.handleDockerEngine)
	s.mux.HandleFunc("GET /api/docker/containers", s.handleDockerContainers)
	s.mux.HandleFunc("POST /api/docker/containers/{id}/action", s.adminOnly(s.handleDockerContainerAction))
	s.mux.HandleFunc("DELETE /api/docker/containers/{id}", s.adminOnly(s.handleDockerRemoveContainer))
	s.mux.HandleFunc("GET /api/docker/containers/{id}/logs", s.adminOnly(s.handleDockerLogs))

	// Docker Images
	s.mux.HandleFunc("GET /api/docker/images", s.handleDockerImages)
	s.mux.HandleFunc("POST /api/docker/images/pull", s.adminOnly(s.handleDockerPullImage))
	s.mux.HandleFunc("DELETE /api/docker/images/{id}", s.adminOnly(s.handleDockerRemoveImage))
	s.mux.HandleFunc("POST /api/docker/images/prune", s.adminOnly(s.handleDockerPruneImages))

	// Docker Compose (Apple engine: served through the experimental mocker
	// bridge; see composeEngine middleware)
	s.mux.HandleFunc("GET /api/docker/compose", s.composeEngine(s.handleDockerComposeList))
	s.mux.HandleFunc("GET /api/docker/compose/{name}", s.adminOnly(s.composeEngine(s.handleDockerComposeGetYaml)))
	s.mux.HandleFunc("POST /api/docker/compose/deploy", s.adminOnly(s.composeEngine(s.handleDockerComposeDeploy)))
	s.mux.HandleFunc("POST /api/docker/compose/deploy/stream", s.adminOnly(s.composeEngine(s.handleDockerComposeDeployStream)))
	s.mux.HandleFunc("POST /api/docker/compose/{name}/action", s.adminOnly(s.composeEngine(s.handleDockerComposeAction)))
	s.mux.HandleFunc("DELETE /api/docker/compose/{name}", s.adminOnly(s.composeEngine(s.handleDockerComposeDelete)))

	// Experimental Apple Compose bridge (mocker)
	s.mux.HandleFunc("GET /api/docker/apple-compose", s.handleAppleComposeGet)
	s.mux.HandleFunc("POST /api/docker/apple-compose", s.adminOnly(s.handleAppleComposeSet))

	// Docker Networks & Mirrors
	s.mux.HandleFunc("GET /api/docker/networks", s.handleDockerNetworks)
	s.mux.HandleFunc("GET /api/docker/mirrors", s.handleDockerGetMirrors)
	s.mux.HandleFunc("POST /api/docker/mirrors", s.adminOnly(s.handleDockerSetMirrors))

	// 5. Apps (installs run through docker compose; under the Apple engine
	// they are served by the mocker bridge or blocked per composeEngine)
	s.mux.HandleFunc("GET /api/apps", s.handleAppsList)
	s.mux.HandleFunc("GET /api/apps/{id}/config", s.adminOnly(s.handleAppGetConfig))
	s.mux.HandleFunc("POST /api/apps/{id}/install", s.adminOnly(s.composeEngine(s.handleAppInstall)))
	s.mux.HandleFunc("POST /api/apps/{id}/install/custom", s.adminOnly(s.composeEngine(s.handleAppInstallCustomStream)))
	s.mux.HandleFunc("POST /api/apps/custom", s.adminOnly(s.handleAppCustomAdd))
	s.mux.HandleFunc("DELETE /api/apps/custom/{id}", s.adminOnly(s.handleAppCustomDelete))
	s.mux.HandleFunc("POST /api/apps/sync", s.adminOnly(s.handleAppStoreSync))
	s.mux.HandleFunc("POST /api/apps/{id}/start", s.adminOnly(s.composeEngine(s.handleAppStart)))
	s.mux.HandleFunc("POST /api/apps/{id}/stop", s.adminOnly(s.composeEngine(s.handleAppStop)))
	s.mux.HandleFunc("POST /api/apps/{id}/restart", s.adminOnly(s.composeEngine(s.handleAppRestart)))
	s.mux.HandleFunc("POST /api/apps/{id}/uninstall", s.adminOnly(s.composeEngine(s.handleAppUninstall)))
	s.mux.HandleFunc("GET /api/apps/{id}/logs", s.adminOnly(s.composeEngine(s.handleAppLogs)))

	// 6. Samba
	s.mux.HandleFunc("GET /api/samba/status", s.handleSambaStatus)
	s.mux.HandleFunc("POST /api/samba/shares", s.adminOnly(s.handleSambaShareAddOrUpdate))
	s.mux.HandleFunc("PUT /api/samba/shares/{id}", s.adminOnly(s.handleSambaShareAddOrUpdate))
	s.mux.HandleFunc("POST /api/samba/shares/{id}/toggle", s.adminOnly(s.handleSambaShareToggle))
	s.mux.HandleFunc("DELETE /api/samba/shares/{id}", s.adminOnly(s.handleSambaShareDelete))
	s.mux.HandleFunc("POST /api/samba/service/toggle", s.adminOnly(s.handleSambaServiceToggle))
	s.mux.HandleFunc("POST /api/samba/service/restart", s.adminOnly(s.handleSambaServiceRestart))
	s.mux.HandleFunc("POST /api/samba/password", s.adminOnly(s.handleSambaPassword))

	// 7. Web Terminal & File System
	s.mux.HandleFunc("GET /api/terminal/ws", s.adminOnly(s.handleTerminalWS))
	s.mux.HandleFunc("POST /api/terminal/session/close", s.adminOnly(s.handleTerminalSessionClose))
	s.mux.HandleFunc("GET /api/terminal/files", s.handleTerminalFilesList)
	s.mux.HandleFunc("GET /api/terminal/files/read", s.handleTerminalFileRead)
	s.mux.HandleFunc("POST /api/terminal/files/write", s.adminOnly(s.handleTerminalFileWrite))
	s.mux.HandleFunc("POST /api/terminal/files/mkdir", s.adminOnly(s.handleTerminalFileMkdir))
	s.mux.HandleFunc("POST /api/terminal/files/upload", s.adminOnly(s.handleTerminalFileUpload))
	s.mux.HandleFunc("POST /api/terminal/files/rename", s.adminOnly(s.handleTerminalFileRename))
	s.mux.HandleFunc("DELETE /api/terminal/files", s.adminOnly(s.handleTerminalFileDelete))
	s.mux.HandleFunc("GET /api/terminal/files/download", s.handleTerminalFileDownload)
	s.mux.HandleFunc("GET /api/terminal/files/download-archive", s.adminOnly(s.handleTerminalFilesBatchDownload))
	s.mux.HandleFunc("GET /api/terminal/files/archive-capabilities", s.handleTerminalArchiveCapabilities)
	s.mux.HandleFunc("POST /api/terminal/files/archive", s.adminOnly(s.handleTerminalArchive))
	s.mux.HandleFunc("GET /api/terminal/files/raw", s.handleTerminalFileRaw)
	s.mux.HandleFunc("POST /api/terminal/files/copy", s.adminOnly(s.handleTerminalFilesCopy))
	s.mux.HandleFunc("POST /api/terminal/files/move", s.adminOnly(s.handleTerminalFilesMove))
	s.mux.HandleFunc("POST /api/terminal/files/trash", s.adminOnly(s.handleTerminalFilesTrash))
	s.mux.HandleFunc("GET /api/terminal/files/trash", s.handleTerminalFilesTrashList)
	s.mux.HandleFunc("POST /api/terminal/files/restore", s.adminOnly(s.handleTerminalFilesRestore))
	s.mux.HandleFunc("POST /api/terminal/files/trash/delete", s.adminOnly(s.handleTerminalFilesTrashDelete))
	s.mux.HandleFunc("POST /api/terminal/files/empty-trash", s.adminOnly(s.handleTerminalFilesEmptyTrash))

	// 8. System Security, Users & SSH
	s.mux.HandleFunc("GET /api/system/users", s.adminOnly(s.handleListUsers))
	s.mux.HandleFunc("POST /api/system/users", s.adminOnly(s.handleCreateUser))
	s.mux.HandleFunc("POST /api/system/users/{username}/password", s.adminOnly(s.handleUpdateUserPassword))
	s.mux.HandleFunc("DELETE /api/system/users/{username}", s.adminOnly(s.handleDeleteUser))
	s.mux.HandleFunc("POST /api/system/root/password", s.adminOnly(s.handleUpdateRootPassword))
	s.mux.HandleFunc("GET /api/system/ssh", s.adminOnly(s.handleGetSSHConfig))
	s.mux.HandleFunc("POST /api/system/ssh", s.adminOnly(s.handleUpdateSSHConfig))
	s.mux.HandleFunc("POST /api/system/ssh/bootstrap", s.adminOnly(s.handleBootstrapSSH))
	s.mux.HandleFunc("POST /api/system/ssh/toggle", s.adminOnly(s.handleToggleSSH))
	s.mux.HandleFunc("POST /api/system/ssh/keys/generate", s.adminOnly(s.handleGenerateSSHRootKey))
	s.mux.HandleFunc("GET /api/system/ssh/keys", s.adminOnly(s.handleGetSSHAuthorizedKeys))
	s.mux.HandleFunc("POST /api/system/ssh/keys/add", s.adminOnly(s.handleAddSSHAuthorizedKey))
	s.mux.HandleFunc("DELETE /api/system/ssh/keys", s.adminOnly(s.handleClearSSHAuthorizedKeys))
	s.mux.HandleFunc("GET /api/system/terminal/settings", s.handleGetTerminalSettings)
	s.mux.HandleFunc("POST /api/system/terminal/settings", s.adminOnly(s.handleUpdateTerminalSettings))
	s.mux.HandleFunc("GET /api/system/terminal/skills", s.adminOnly(s.handleGetTerminalSkills))
	s.mux.HandleFunc("POST /api/system/terminal/skills", s.adminOnly(s.handleUpdateTerminalSkills))

	// 9. Homepage service navigation
	s.mux.HandleFunc("GET /api/service-shortcuts", s.handleServiceShortcutsList)
	s.mux.HandleFunc("POST /api/service-shortcuts", s.adminOnly(s.handleServiceShortcutCreate))
	s.mux.HandleFunc("PUT /api/service-shortcuts/{id}", s.adminOnly(s.handleServiceShortcutUpdate))
	s.mux.HandleFunc("DELETE /api/service-shortcuts/{id}", s.adminOnly(s.handleServiceShortcutDelete))
	s.mux.HandleFunc("POST /api/service-shortcuts/reorder", s.adminOnly(s.handleServiceShortcutReorder))

	// 10. Web Console Authentication & User Management
	s.mux.HandleFunc("POST /api/auth/login", s.handleAuthLogin)
	s.mux.HandleFunc("GET /api/auth/status", s.handleAuthStatus)
	s.mux.HandleFunc("POST /api/auth/setup", s.handleAuthSetup)
	s.mux.HandleFunc("POST /api/auth/logout", s.handleAuthLogout)
	s.mux.HandleFunc("GET /api/auth/me", s.handleAuthMe)
	s.mux.HandleFunc("POST /api/auth/change-pwd", s.handleAuthChangePassword)
	s.mux.HandleFunc("GET /api/auth/users", s.handleAuthListUsers)
	s.mux.HandleFunc("POST /api/auth/users", s.handleAuthCreateUser)
	s.mux.HandleFunc("PUT /api/auth/users/{id}", s.handleAuthUpdateUser)
	s.mux.HandleFunc("DELETE /api/auth/users/{id}", s.handleAuthDeleteUser)
}
